version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: verification_db
      POSTGRES_USER: verification_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - verification-network

  web:
    build: ./web
    command: gunicorn web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web:/code
      - ./static:/code/static
    env_file:
      - ./web/.env
    depends_on:
      - db
    networks:
      - verification-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    depends_on:
      - web
    networks:
      - verification-network

volumes:
  postgres_data:

networks:
  verification-network:
